name         'mcanevet-btsync'
version      '0.2.1'
dependency   'puppetlabs/stdlib', '>= 0.0.1'
dependency   'puppetlabs/apt', '>= 0.0.1'
dependency   'theforeman/concat_native', '>= 0.0.1'
source       'https://github.com/mcanevet/puppet-btsync'
author       'Mickaël Canévet'
license      'Apache 2.0'
summary      'Puppet btsync module'
description  'Puppet module for BitTorrent Sync'
project_page 'https://github.com/mcanevet/puppet-btsync'
