name         'mcanevet-btsync'
version      '0.1.0'
dependency   'puppetlabs/stdlib', '>= 0.1.3'
source       'https://github.com/mcanevet/puppet-btsync'
author       'Mickaël Canévet'
license      'Apache 2.0'
summary      'Puppet btsync module'
description  'Puppet module for BitTorrent Sync'
project_page 'https://github.com/mcanevet/puppet-btsync'
